version: "3.9"

services:
  reverse-proxy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - superset
    restart: unless-stopped

  superset:
    image: ghcr.io/lyric2249/superset-custom:latest   # CI에서 푸시할 이미지
    env_file: .env                                   # 서버 로컬에서 제공
    expose:
      - "8088"                                       # 외부 미공개
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py:ro
      - ./boot.sh:/docker-entrypoint-initdb.d/10_boot.sh:ro
    depends_on:
      - postgres
      - redis
    user: "1000:1000"
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  pg_data:
  superset_home:
