services:
  reverse-proxy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - superset
    restart: unless-stopped



  superset:
    image: ghcr.io/lyric2249/superset-custom:latest   # CI에서 푸시할 이미지
    env_file: .env                                   # 서버 로컬에서 제공
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - SUPERSET_WEBSERVER_BASEURL=https://${PUBLIC_HOST}/ss
    expose:
      - "8088"                                       # 외부 미공개
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py:ro
      - ./boot.sh:/docker-entrypoint-initdb.d/10_boot.sh:ro
    depends_on:
      - postgres-meta
      - redis
    user: "1000:1000"
    restart: unless-stopped




  postgres-meta:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - meta_pg:/var/lib/postgresql/data
    restart: unless-stopped



  postgres-data:
    image: postgres:17
    environment:
      POSTGRES_USER: data_admin
      POSTGRES_PASSWORD: data_pw
      POSTGRES_DB: analytics
    volumes:
      - data_pg:/var/lib/postgresql/data
    ports: ["5434:5432"]



  redis:
    image: redis:7
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  # pg_data:
  superset_home:
  meta_pg:
  data_pg:

