name: Build Superset
on:
  push:
    paths: ['dockers/superset/**']
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./dockers/superset
          file: ./dockers/superset/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/superset-custom:latest
            ghcr.io/${{ github.repository_owner }}/superset-custom:${{ github.sha }}
          build-args: |
            BASE_TAG=3.1.0
          cache-from: type=gha
          cache-to: type=gha,mode=max
